//ACCOUNTS
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAIL = "FETCH_ACCOUNTS_FAIL";
export const FETCH_ACCOUNTS_LOAD = "FETCH_ACCOUNTS_LOAD";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";
export const CREATE_ACCOUNT_LOAD = "CREATE_ACCOUNT_LOAD";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_FAIL = "UPDATE_ACCOUNT_FAIL";
export const UPDATE_ACCOUNT_LOAD = "UPDATE_ACCOUNT_LOAD";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL";
export const DELETE_ACCOUNT_LOAD = "DELETE_ACCOUNT_LOAD";

//TRANSACTIONS
export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_FAIL = "FETCH_TRANSACTIONS_FAIL";
export const FETCH_TRANSACTIONS_LOAD = "FETCH_TRANSACTIONS_LOAD";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAIL = "CREATE_TRANSACTION_FAIL";
export const CREATE_TRANSACTION_LOAD = "CREATE_TRANSACTION_LOAD";
export const CREATE_TRANSACTION_ROW_SUCCESS = "CREATE_TRANSACTION_ROW_SUCCESS";
export const CREATE_TRANSACTION_ROW_LOAD = "CREATE_TRANSACTION_ROW_LOAD";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAIL = "UPDATE_TRANSACTION_FAIL";
export const UPDATE_TRANSACTION_LOAD = "UPDATE_TRANSACTION_LOAD";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAIL = "DELETE_TRANSACTION_FAIL";
export const DELETE_TRANSACTION_LOAD = "DELETE_TRANSACTION_LOAD";
export const DELETE_TRANSACTION_ROW_SUCCESS = "DELETE_TRANSACTION_ROW_SUCCESS";
export const DELETE_TRANSACTION_ROW_LOAD = "DELETE_TRANSACTION_ROW_LOAD";
