apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetly-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgetly-client
  template:
    metadata:
      labels:
        app: budgetly-client
    spec:
      containers:
        - name: budgetly-client
          image: registry.digitalocean.com/docrnuagirprod/budgetly-client:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
      imagePullSecrets:
        - name: docrnuagirprod